# Generated by Django 4.0.2 on 2022-05-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_avatar_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(help_text='Desribe yourself with 500 words only', max_length=500),
        ),
    ]
