# Generated by Django 4.0.2 on 2022-02-04 06:33

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='noimage.jpg', upload_to='employee_pic')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('email', models.EmailField(max_length=160)),
                ('phoneno', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], default=None, max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('state', models.CharField(choices=[('DL', 'Delhi'), ('FBD', 'Faridabad'), ('MP', 'Madhya Pradesh'), ('AN', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh')], default=None, max_length=50)),
                ('designation', models.CharField(choices=[('Designer', 'Designer'), ('Manager', 'Manager'), ('Developer', 'Developer'), ('Hr Manager', 'Hr Manager'), ('CEO', 'CEO'), ('MD', 'MD'), ('Director', 'Director'), ('Secretary', 'Secretary')], default=None, max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Upload_employee_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='emp_upload_file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Upload Employee Details',
            },
        ),
    ]
